# Generated by Django 5.0.3 on 2024-04-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='imgURL',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
