# Generated by Django 5.0.3 on 2024-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cart_imgurl_alter_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='imgURL',
            field=models.CharField(),
        ),
    ]
